import Head from "next/head";
import Image from "next/image";
// import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }: { data: [] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img src="" alt=""></img>
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about">About us</Link>
        </nav>
      </header>
      <main className={styles.main}>
        {data.map(
          (
            e: {
              id: string;
              title: string;
              description: string;
              image: string;
            },
            i
          ) => (
            <Link key={i} href={`/events/${e.id}`}>
              <Image width={200} height={200} src={e.image} alt="" />
              <h2>{e.title}</h2>
              <p>{e.description}</p>
            </Link>
          )
        )}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("../../data/data.json");
  console.log(events_categories);

  return {
    props: {
      data: events_categories,
    },
  };
}
